// Code generated by "stringer -type TorrentState"; DO NOT EDIT.

package bittorrent

import "strconv"

func _() {
	// An "invalid array index" compiler error signifies that the constant values have changed.
	// Re-run the stringer command to generate them again.
	var x [1]struct{}
	_ = x[TorrentStateStopped-0]
	_ = x[TorrentStateVerifying-1]
	_ = x[TorrentStateStarted-2]
}

const _TorrentState_name = "TorrentStateStoppedTorrentStateVerifyingTorrentStateStarted"

var _TorrentState_index = [...]uint8{0, 19, 40, 59}

func (i TorrentState) String() string {
	if i >= TorrentState(len(_TorrentState_index)-1) {
		return "TorrentState(" + strconv.FormatInt(int64(i), 10) + ")"
	}
	return _TorrentState_name[_TorrentState_index[i]:_TorrentState_index[i+1]]
}
